bird-house/ansible-wps-playbook

docs/source/appendix.rst
docs/source/testing.rst
playbook.yml
roles/pywps/handlers/main.yml
roles/pywps/tasks/main.yml

This PR fixes #13.
Changes:
* Update docs with vagrant tests.
* Enabled restart of supervisor (needs latest supervisor conda role).

restart supervisor after update (#13)

---

docs/source/custom_playbook.rst
group_vars/all
playbook.yml
vars/main.yml

This PR fixes issue #23.
Changes:
* Added variable `db_install_postgresql` to make postgres installation optional.
* Fixed db_name default value (unique for each WPS).
* Updated docs.

postgres db install is optional (#23)

---

.gitignore
.travis.yml
bootstrap.sh
docs/source/appendix.rst
etc/sample-sqlite.yml
group_vars/all
playbook.yml
requirements.yml
roles/pywps/tasks/main.yml
roles/pywps/templates/pywps.cfg
vars/main.yml

This PR fixes #34.
Changes:
*  fixed `bootstrap.sh` for CentOS 6 to enable downloads of roles from Ansible Galaxy.
* added support for sqlite: `db_install_sqlite: false`.
* using `ANXS.postgresql` role with support for CentOS 6.
* enabled travis tests for CentOS 6/7 and Ubuntu 18.04.

support for centos 6.x (#34)

---

group_vars/all
roles/pywps/templates/pywps.cfg

This PR allows to overwrite the default `outputurl` for each WPS installation.

make outputurl configurable

---

ansible.cfg
docs/source/preparing.rst
docs/source/testing.rst
roles/pywps/templates/pywps.cfg

This PR adds a fix to issue #34.
Changes:
* Updated `pywps.cfg` template to support Python 2.6 on CentOS 6.
* Updated documentation with an example for Vagrant without provisioning.

fix pywps.cfg template for python 2.6 (#34)

---

docs/source/preparing.rst
docs/source/testing.rst
requirements.yml

This PR fixes issue #39.
Changes:
* download all roles as `tar.gz` from GitHub to prevent firewall/proxy issues with ansible galaxy.
* typos in docs.

download roles as tar.gz (#39)

---

.gitignore
docs/source/appendix.rst
etc/sample-certs.yml
group_vars/all
playbook.yml
requirements.yml
roles/certs/tasks/main.yml
roles/common/tasks/Debian.yml
roles/common/tasks/RedHat.yml
roles/pywps/templates/nginx.conf.j2
roles/pywps/templates/pywps.cfg
vars/main.yml

This PR fixes issue #30.
Changes:
* Added variable `wps_enable_https` to configure Nginx with HTTPS.
* Added role `jdauphant.ssl-certs` to generated self-signed certs or add local certs.
* Allow SSL client certificate verification.

enable https (#30)

---

etc/sample-certs.yml
roles/pywps/templates/nginx.conf.j2
roles/pywps/templates/pywps.cfg

This PR is an update to issue #30.
Changes:
* `sethomedir` in pywps config can be set.
* disabled `Http-X-Ssl-Client-Cert` in nginx config.
Changes are necessary to transfer proxy certificate for opendap.

sethomedir (#30)

---

roles/common/tasks/Debian.yml
roles/common/tasks/RedHat.yml

This PR updates the package installation for `yum` and `apt`. Using loops is deprecated.

fix package install

---

bootstrap.sh
docs/source/preparing.rst

This PR fixes `bootstrap.sh` on CentOS 6 and adds `pip` note to the docs.

fix bootstrap

---

.gitignore
etc/sample-cp4cds_load-balancer.yml
group_vars/all
requirements.yml
roles/common/tasks/main.yml

This PR adds the wps user uid/gid options to the `group_vars/all` config. uid/gid can be omitted and will be set automatically when not set.
Fix #56.

added user uid/gid to config

---

docs/source/configuration.rst
etc/sample-emu-with-conda-spec.yml
etc/sample-vagrant.yml
roles/pywps/tasks/conda.yml
vars/main.yml

This PR fixes issues #71.
Changes:
* adds option `conda_env_use_spec` to use conda spec file.
* updated docs.
* skipped `git.changed` condition for conda tasks.

Issue 71 use conda spec

---

roles/pywps/tasks/folders.yml
roles/pywps/templates/gunicorn.py.j2
roles/pywps/templates/nginx.conf.j2
roles/twitcher/tasks/folders.yml
roles/twitcher/templates/nginx.conf.j2
roles/twitcher/templates/twitcher.ini.j2
vars/main.yml

This PR fixes issue #54.
Changes:
* socket is created in `/var/lib/pywps` and `/var/lib/twitcher`.
* update gunicorn config.

fix service restart

---

roles/pywps/tasks/config.yml
roles/pywps/tasks/folders.yml
roles/pywps/templates/gunicorn.py.j2
roles/pywps/templates/nginx.conf.j2
roles/pywps/templates/tmpfiles.config.j2
roles/twitcher/tasks/config.yml
roles/twitcher/tasks/folders.yml
roles/twitcher/templates/tmpfiles.config.j2
vars/main.yml

This PR fixes #78. It adds a `tmpfiles.d` config for both pywps and twitcher to create `/run/pywps` and `/run/twitcher` folders.

added tmpfiles.d config for pywps and twitcher

---

roles/pywps/tasks/config.yml
roles/twitcher/tasks/config.yml

This PR fixes the `tmpfiles.d` configuration name.
See #78 and PR #80.

fix tmpfiles config

---

etc/sample-rook.yml

added example config for rook. Can be tested (without data) with vagrant:
```
$ git clone ...
$ cd ansible-wps-playbook
$ make roles # get ansible roles
$ ln -s etc/sample-rook.yml custom.yml
$ vagrant up
http://192.168.128.100:5000/wps?service=WPS&request=GetCapabilities
```
See docs: 
https://ansible-wps-playbook.readthedocs.io/en/latest/testing.html#test-ansible-with-vagrant

added rook example

---

roles/pywps/tasks/conda.yml

This PR fixes #96. It uses `pip` to install additional packages for deployment like `gunicorn`.

use pip to install additional packages

---

etc/vagrant-cluster-with-rook.yml
group_vars/all
playbook.yml
roles/demo/tasks/main.yml
roles/pywps/tasks/config.yml
roles/pywps/templates/roocs.demo.ini.j2
roles/pywps/templates/roocs.ini.j2

Changes:
* Use `data_dir` in demo mode to install `mini_esgf_data`.
* Added `roocs.demo.ini` template using `data_dir` in demo mode.
* Using `roocs.ini` template in normal mode.
* Added example with `epel_repo_disable: false`. See: [ansible-role-repo-epel](https://github.com/geerlingguy/ansible-role-repo-epel#role-variables)

Fix demo mode

---

roles/pywps/templates/nginx.conf.j2

This PR adds a `health/` endpoint to be used by load-balancers. It currently just reports that the service is running.

added inital health check endpoint

---

.travis.yml
group_vars/all
roles/common/tasks/RedHat.yml
roles/pywps/tasks/cronjob.yml
roles/pywps/tasks/webservice.yml
roles/pywps/templates/nginx.conf.j2

This PR adds a task to configure cronjobs to clear wps outputs.
It is using the ansible cron module:
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/cron_module.html
It adds two variables:
```
wps_cronjob_disabled: yes
wps_outputs_keep_days: 30
```
cronjobs are disabled by default.

Add cronjob

---

roles/pywps/tasks/cronjob.yml
roles/pywps/templates/restart-pywps.sh.j2

This PR adds a cronjob to restart pywps. This is necessary to clean gunicorn processes.

Clean gunicorn procs

---

etc/rook_dkrz.yml
etc/sample-rook.yml
group_vars/all
roles/pywps/templates/nginx.conf.j2

This PR adds optional access control with nginx config. The execution of a wps process can be restricted to specific IP ranges:
```
wps_enable_acl: true
wps_acl_allow:
- 192.168.128.1/24
```

nginx access control

---

group_vars/all
roles/pywps/tasks/conda.yml
roles/pywps/templates/gunicorn.py.j2

This PR makes gunicorn workers configurable:
https://docs.gunicorn.org/en/stable/settings.html
```
gunicorn_workers: 5  # rule of thumb: 2 * CPUs + 1
gunicorn_worker_class: 'sync'  # or "gevent", needs gevent
```
`sync` is default. One can also choose `gevent`. `gevent` is installed in the conda environment.

Gunicorn config

---

Makefile
extra_vars.yml
group_vars/all.yml
playbook.yml

This PR uses `extra_vars.yml` to overwrite variables of the miniconda role.
This is necessary because we can't use miniconda anymore and need to dowload miniforge.

using extra_vars.yml
