.gitignore
.travis.yml
Makefile
README.rst
Vagrantfile
playbook.yml
roles/common/tasks/Debian.yml
roles/common/tasks/RedHat.yml
roles/common/tasks/main.yml
roles/pywps/tasks/main.yml
run_docker.sh
tests/README.md
tests/test_playbook.sh

This PR fixes issue #5.
Changes:
* Added travis with docker test suite for playbook.
* Updated `run_docker.sh`

Fix #5: enabled travis tests.

---

group_vars/all
playbook.yml
roles/common/tasks/main.yml
roles/pywps/tasks/main.yml
roles/pywps/templates/gunicorn.py.j2
roles/pywps/templates/nginx.conf.j2

This PR fixes #10.
Changes:
* Added `wps_user` and  `wps_group` to configure service user.
* Updates folder and file permissions.

allow user configuration (#10)

---

group_vars/all
roles/pywps/tasks/main.yml

This PR fixes issue #12.
Changes:
* Added `conda_env_prefix` to configure the Conda environment.

Added conda_env_prefix (#12)

---

requirements.yml
vars/main.yml

Changes:
* pin supervisor role 2.0.2.
* disable supervisor password.

updated supervisor and disabled password (#31)

---

bootstrap.sh

This PR fixes issue #50.
It adds an upgrade script for Ansible on RedHat 6 ... like proposed in the issue description.

added upgrade script for ansible on rh6

---

docs/source/configuration.rst
etc/sample-vagrant.yml
group_vars/all
roles/pywps/tasks/config.yml
roles/pywps/templates/pywps.cfg.j2

This PR fixes #60.
Changes:
* using `extra_config` to extend the pywps configuration.
* update config docs.

using extra_config in pywps template

---

vars/main.yml

This PR fixes #65. Added `wps_group` to nginx user config.

added wps_group to nginx config

---

group_vars/all
roles/common/tasks/main.yml

This PR fixes #64. 
Changes:
* Added a flag `wps_add_user` to skip task "wps add user".

added flag wps_add_user

---

docs/source/configuration.rst
etc/sample-certs.yml
etc/sample-cp4cds_load-balancer.yml
etc/sample-multiple-with-shared-fileserver.yml
etc/sample-vagrant.yml
group_vars/all
roles/pywps/templates/pywps.cfg.j2

This PR fixes #68. 
Changes:
* updated pywps template to support load-balancing config.
* updated docs.
* updated examples.

added support for load-balancing config

---

docs/source/conf.py
docs/source/configuration.rst
etc/sample-postgres.yml
etc/sample-vagrant.yml
vars/main.yml

Updated docs and examples for database configuration.

updated docs for db config

---

Makefile
etc/sample-emu-with-twitcher.yml
etc/sample-magic.yml
group_vars/all
roles/common/tasks/main.yml
roles/pywps/tasks/main.yml
roles/pywps/templates/gunicorn.py.j2
roles/pywps/templates/run.sh.j2
roles/twitcher/tasks/main.yml
roles/twitcher/templates/nginx.conf.j2
roles/twitcher/templates/twitcher.ini.j2
vars/main.yml

This PR is an update to the latest twitcher version.

update for twitcher

---

etc/sample-emu.yml
etc/sample-vagrant.yml
requirements.yml

This PR skips the version of the required roles.

don't pin roles version

---

etc/sample-emu.yml
etc/sample-vagrant.yml
vars/main.yml

Enabled postgres password encryption necessary for postgres>=10.

fixed postgres users config

---

etc/sample-twitcher-keycloak.yml
etc/sample-twitcher-standalone.yml
roles/twitcher/templates/twitcher.ini.j2
vars/main.yml

This PR updates the twitcher config template with keycloak options. It adds also some twitcher examples (twitcher installation without wps).

added keycloak config

---

vars/main.yml

This PR adds extra mime types to the nginx config.

added extra mime-types

---

docs/source/live.rst
etc/myhost.cfg
roles/pywps/tasks/conda.yml

This PR fixes the pip installation ... see also #96.

fixed pip install, updated docs

---

etc/sample-emu-with-scheduler.yml
group_vars/all
roles/pywps/tasks/conda.yml
roles/pywps/templates/pywps.cfg.j2

This PR adds the processing mode to the config to enable the scheduler extension.

added scheduler config

---

roles/pywps/tasks/clean.yml
roles/pywps/tasks/webservice.yml

Added task to clean service configs (nginx, supervisor) before update. Needed when a wps service is removed from the installation.

added clean task

---

Makefile
docs/source/appendix.rst
docs/source/deploy.rst
docs/source/examples.rst
docs/source/testing.rst
hosts
roles/pywps/tasks/conda.yml

Changes:
* workaround: added missing sphinx for pywps autodoc extension
* added hosts inventory for local deployment
* updated docs

Fix local deployment

---

etc/sample-rook.yml
etc/vagrant-cluster-with-rook.yml
group_vars/all
roles/pywps/tasks/config.yml
roles/pywps/templates/gunicorn.py.j2
roles/pywps/templates/roocs.ini.j2

This PR adds `roocs.ini` config for [roocs](https://github.com/roocs).

Update for roocs

---

playbook.yml

don't run epel tasks when disabled.

skip epel setup when not used

---

etc/sample-emu-debug.yml
etc/sample-vagrant.yml
etc/vagrant-cluster-with-rook.yml
group_vars/all
roles/pywps/templates/pywps.cfg.j2

The PR adds the `cleantempdir` pywps option to the pywps config template. Updated examples.

added cleantempdir option

---

etc/rook_dkrz.yml
etc/vagrant-cluster-with-rook.yml
group_vars/all
roles/pywps/templates/pywps.cfg.j2

This PR adds a config parameter `drmaa_native_specification` for the job scheduler used by pywps.

update for drmaa config

---

etc/rook_dkrz.yml
etc/vagrant-cluster-with-rook.yml
group_vars/all
roles/pywps/tasks/conda.yml

This PR updates the conda env installation task.
Changes:
* conda env will *always* be removed before new install
* update conda install using `spec-list.txt`: https://www.anaconda.com/blog/moving-conda-environments

updated task for conda env install

---

etc/cronjob_0pywps.sh

This PR adds an example for a cronjob to clean up outputs.

added cronjob example

---

.gitignore
.travis.yml
group_vars/all
playbook.yml
requirements.yml

This PR adds logrotate for pywps log files.
It using the ansible logrotate module:
https://galaxy.ansible.com/arillso/logrotate
It is configured to daily rotate log files `/var/log/pywps/*.log`.

added logrotate for pywps

---

group_vars/all
roles/pywps/templates/nginx.conf.j2

Changes:
* added nginx cache for `GetCapabilities` and `DescribeProcess` requests.
* redirect `health/` endpoint to `GetCapabilities` request.
* upload logrotate config.

added nginx cache

---

.gitignore
Makefile
ansible.cfg
docs/source/examples.rst
etc/rook_dkrz.yml
etc/sample-rook.yml
group_vars/all
requirements.yml
roles/pywps/tasks/cronjob.yml

This PR adds the `MAILTO` variable to the cron job environment. It uses [cronvar](https://docs.ansible.com/ansible/latest/collections/community/general/cronvar_module.html) from the ansible collections.

Update cron env

---

scripts/get_route53_ips.py

This PR adds a script to filter route53 ips used for the health check:
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/route-53-ip-addresses.html

added route53_ips script

---

etc/rook_dkrz.yml
etc/sample-rook.yml
etc/vagrant-cluster-with-rook.yml
group_vars/all
roles/demo/tasks/main.yml
roles/pywps/tasks/config.yml
roles/pywps/templates/roocs.default.ini.j2
roles/pywps/templates/roocs.demo.ini.j2
roles/pywps/templates/roocs.dkrz.ini.j2

This PR adds a `site` option to enable site specific `roocs.ini` configs.

use site config

---

roles/pywps/templates/roocs.ceda.ini.j2

Added: roocs.ceda.ini.j2

---

group_vars/all

removed unused ssl_certs parameters

---

roles/pywps/tasks/conda.yml
roles/pywps/tasks/cronjob.yml
roles/pywps/templates/smoke.sh.j2

Added a script for smoke tests.

Add rook smoke

---

roles/pywps/templates/nginx.conf.j2
roles/roocs/templates/roocs.dkrz.ini.j2

* Changed order of nginx acl checks.
* Added data node for dkrz cmip6 in `roocs.ini`

Fix nginx acl

---

roles/pywps/templates/pywps.cfg.j2

This PR updates the `pywps.cfg` to allow overwrite of provider and contact.

update metadata in pywps.cfg

---

group_vars/all
roles/pywps/templates/pywps.cfg.j2

Added pywps option for copy-function to template.
See in pywps: https://github.com/geopython/pywps/pull/584

added pywps copy-function

---

group_vars/all
roles/pywps/templates/gunicorn.py.j2
roles/pywps/templates/nginx.conf.j2
roles/pywps/templates/pywps.cfg.j2

This PR adds configuration parameters for nginx/gunicorn timeouts. In addition it adds defaults for wps log files:
```
wps_log_dir: /var/log/pywps
wps_http_log_dir: /var/log/nginx
```

Timeout config

---

group_vars/all

update default drmaa version

---

etc/rook3_dkrz.yml
etc/rook4_dkrz.yml
group_vars/all
roles/pywps/tasks/cronjob.yml

The PR updates the cron configuration:
* add variable `cron_enabled`
* add variable `cron_user`
* cron jobs are run now hourly

Update cron config
